name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
        python-version: ['2.7', '3.7', '3.9', 'pypy-2.7', 'pypy-3.7']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mock pytest pytest-cov
      - name: Run tests
        run: pytest tests --cov=git_edit_index --cov-report=term --cov-report=html:coverage/html
      - name: Run linting checks
        run: flake8 --ignore=E501 git-edit-index tests/test_git_edit_index.py setup.py
      - name: Report coveralls status
        if: matrix.os == 'ubuntu-20.04' && matrix.python-version == '3.9'
        uses: AndreMiras/coveralls-python-action@v20201129
